/*
 * This source file was generated by the Gradle 'init' task
 */
package desktopapp;


class AppTest {
    @Test void appHasAGreeting() {
        // App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(Object greeting, String string) {
        throw new UnsupportedOperationException("Unimplemented method 'assertNotNull'");
    }
}
